
services:
  web:
    build: .
    environment:
      TZ: Europe/Moscow
    ports:
      - "5000:5000"

  celery:
    build: .
    environment:
      TZ: Europe/Moscow
    command: celery -A celery_file.periodic_app worker --loglevel=info
#
  celery-beat:
    build: .
    environment:
      TZ: Europe/Moscow
    command: celery -A celery_file.periodic_app beat --loglevel=info
#
  flower:
    build: .
    environment:
      TZ: Europe/Moscow
    command: celery -A app.celery flower --port=5555
    ports:
      - "5555:5555"
#
  redis:
    image: "redis:alpine"
    environment:
      TZ: Europe/Moscow
    ports:
      - "6379:6379"